### ISSUE TITLE
Better Discord fails to load completely

### ISSUE THREAD

**Issue by AirplaneA220** [Strencher/BdBrowser#29]
I noticed that the tabs for better discord didn't appear and checked the logs

This error appeared for the extension in the logs

`[BetterDiscord] [FronEnd] Failed to load BD:
 TypeError: Cannot read properties of undefined (reading 'ActionTypes')
    at eval (eval at callback (frontend.js:1:28740), <anonymous>:1:331914)
    at eval (eval at callback (frontend.js:1:28740), <anonymous>:1:370453)
    at eval (eval at callback (frontend.js:1:28740), <anonymous>:1:370457)
    at eval (eval at callback (frontend.js:1:28740), <anonymous>:1:370462)
    at callback (frontend.js:1:28740)
    at e5880ab2ccec6da98ca7.js:4242:635
    at Set.forEach (<anonymous>)
    at t._dispatch (e5880ab2ccec6da98ca7.js:4242:607)
    at t._dispatchWithLogging (e5880ab2ccec6da98ca7.js:4241:804)
    at t._dispatchWithDevtools (e5880ab2ccec6da98ca7.js:4241:415)
    at t.dispatch (e5880ab2ccec6da98ca7.js:4241:348)
    at e5880ab2ccec6da98ca7.js:2986:938
    at t.time (e5880ab2ccec6da98ca7.js:4089:172)
    at e5880ab2ccec6da98ca7.js:2986:887
    at ve (e5880ab2ccec6da98ca7.js:2983:232)
    at e5880ab2ccec6da98ca7.js:2986:312
    at t.time (e5880ab2ccec6da98ca7.js:4089:172)
    at t.<anonymous> (e5880ab2ccec6da98ca7.js:2986:287)
    at a.emit (e5880ab2ccec6da98ca7.js:4996:438)
    at n._handleDispatchWithoutQueueing (e5880ab2ccec6da98ca7.js:1757:411)
    at n._handleDispatch (e5880ab2ccec6da98ca7.js:1756:534)
    at e5880ab2ccec6da98ca7.js:1755:435
    at r._onDataReady (e5880ab2ccec6da98ca7.js:1751:129)
    at c.push.t.handleFlushEnd (e5880ab2ccec6da98ca7.js:1743:834)
    at d.push (e5880ab2ccec6da98ca7.js:5758:156)
    at c.push.t.feed (e5880ab2ccec6da98ca7.js:1743:278)
    at WebSocket.<anonymous> (e5880ab2ccec6da98ca7.js:1751:194)`

![image](https://user-images.githubusercontent.com/84548624/182251528-68bb2f95-f7b5-4b73-ba09-99f134465ddd.png)

**Comment by drop-middle-leaves** [comment]
Similar issue however no betterdiscord menu item.
![image](https://user-images.githubusercontent.com/66450509/184753328-f9ba78ce-bef1-4779-942e-09b1d2fed8e9.png)
